  1.旋转向量转旋转矩阵

In [1]:
import cv2
import numpy as np

def rotvector2rot(rotvect):
    Rm = cv2.Rodrigues(rotvect)[0]
    return Rm

retvector = np.array([0.223680285784755,	0.240347886848190,	0.176566110650535])
print(rotvector2rot(retvector))

[[ 0.95604131 -0.14593404  0.2543389 ]
 [ 0.19907538  0.95986385 -0.19756111]
 [-0.21529982  0.23950919  0.94672136]]


In [12]:
point = np.array([1, 0, 0])
print(np.dot(retvector,point.reshape(3, 1)))
print(np.dot(rotvector2rot(retvector),point.reshape(3, 1)))
point.reshape(3, 1)

[0.22368029]
[[ 0.95604131]
 [ 0.19907538]
 [-0.21529982]]


array([[1],
       [0],
       [0]])

2.四元数转欧拉角

In [19]:
from scipy.spatial.transform import Rotation as R

def quaternion2euler(quaternion):
    # R表示旋转矩阵类，from_quat是该类的一个静态方法，quaternion是要转换的四元数。
    r = R.from_quat(quaternion)
    # 'xyz'表示欧拉角的旋转顺序，degrees=True表示输出的欧拉角是以角度为单位而不是弧度。
    euler = r.as_euler('xyz', degrees=True)
    return euler
q = np.array([0.707, 0.0, 0.0, 0.707])
print(quaternion2euler(q))
# 将四元数转换为旋转矩阵
r = R.from_quat(q)
r.as_matrix()

[90.  0.  0.]


array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]])

3.欧拉角转四元数

In [20]:
from scipy.spatial.transform import Rotation as R

def euler2quaternion(euler):
    r = R.from_euler('xyz', euler, degrees=True)
    quaternion = r.as_quat()
    return quaternion


euler = [90, 0, 0]
print(euler2quaternion(euler))


[0.70710678 0.         0.         0.70710678]


  4.欧拉角转旋转矩阵

In [22]:
from scipy.spatial.transform import Rotation as R

def euler2rot(euler):
    r = R.from_euler('xyz', euler, degrees=True)
    rotation_matrix = r.as_matrix()
    return rotation_matrix

euler = [-24.90053735,    6.599459,   -169.1003646]
print(euler2rot(euler))

[[-0.9754533   0.21902821 -0.02274859]
 [-0.18783626 -0.88152702 -0.43316008]
 [-0.11492777 -0.41825442  0.90102988]]


5.旋转矩阵转欧拉角

In [23]:
import numpy as np
import math


def isRotationMatrix(R):
    Rt = np.transpose(R)
    shouldBeIdentity = np.dot(Rt, R)
    I = np.identity(3, dtype=R.dtype)
    n = np.linalg.norm(I - shouldBeIdentity)
    return n < 1e-6

def rot2euler(R):
    assert (isRotationMatrix(R))

    sy = math.sqrt(R[0, 0] * R[0, 0] + R[1, 0] * R[1, 0])

    singular = sy < 1e-6

    if not singular:
        x = math.atan2(R[2, 1], R[2, 2]) * 180 / np.pi
        y = math.atan2(-R[2, 0], sy) * 180 / np.pi
        z = math.atan2(R[1, 0], R[0, 0]) * 180 / np.pi
    else:
        x = math.atan2(-R[1, 2], R[1, 1]) * 180 / np.pi
        y = math.atan2(-R[2, 0], sy) * 180 / np.pi
        z = 0
    return np.array([x, y, z])

rot = np.array([[-1.01749712e-02,  9.99670705e-01, -2.35574076e-02],
 [-9.99890780e-01, -1.04241019e-02, -1.04769347e-02],
 [-1.07190495e-02,  2.34482322e-02,  9.99667586e-01]])

print(rot2euler(rot))


[  1.34368509   0.61416806 -90.58302646]
